project:
  type: book

book:
  title: "R packages development training"
  author: "[Mathieu Depetris](mailto:mathieu.depetris@cnrs.fr)"
  description: |
    Training and material for learning to create your own R package, maintain and distribute it.
  cover-image: images/cover.png
  favicon: images/cover.png
  page-navigation: true

  reader-mode: true
  site-url: https://umr-marbec.github.io/r_packages_development_training/
  repo-url: https://github.com/umr-marbec/r_packages_development_training

  chapters:
  - index.qmd
  - pages/_introduction.qmd

  - part: "Training framework and requirements"
    chapters:
    - pages/01_os_software.qmd
    - pages/02_r_packages_overview.qmd

  - pages/_references.qmd

  appendices:
    - pages/appendices/a_do_define.qmd
  
  page-footer: 
    left: "Copyright 2025, Mathieu Depetris UMR MARBEC" 
    right:
      - text: "DEN website"
        href: https://umr-marbec.github.io/den_pages/
      - text: "UMR MARBEC website"
        href: https://umr-marbec.fr/

bibliography: references/references.bib
csl: references/diabetologia.csl

format:
  html:
    theme: [cosmo, custom.scss]
  pdf:
    documentclass: scrreprt

editor: visual

lang: en-US

execute:
  freeze: auto
